# server config
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: PT60M

# database config
## mongo
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: guitarchive-server
